logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.open: DEBUG
spring:
  resources:
    static-locations:
     - classpath:/resources/static/
     - classpath:/META-INF/resources/
     - classpath:/resources/
     - classpath:/static/
     - classpath:/public/
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev